<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>MorphFaceEditor.Research</AssemblyName>
    <RootNamespace>MorphFaceEditor.Research</RootNamespace>
    <LecDirectory>$(MSBuildThisFileDirectory)..\..\lib\LegendaryExplorerCore</LecDirectory>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\MorphFaceEditor.LegendaryExplorer\MorphFaceEditor.LegendaryExplorer.csproj" />
    <Reference Include="LegendaryExplorerCore">
      <HintPath>$(LecDirectory)\LegendaryExplorerCore.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
