using MorphFaceEditor.Core.Materials;
using MorphFaceEditor.LegendaryExplorer;

namespace MorphFaceEditor.Services;

internal sealed record MetadataText(string Label, string Description);

/// <summary>
/// Authoritative UI names and descriptions for the reviewed metadata corpus.
/// Edit Shared to change every occurrence; use Archetypes or Games only for a genuine variant.
/// </summary>
internal static class MetadataTextCatalog
{
    private static readonly IReadOnlyDictionary<string, string> Aliases =
        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["ASA_HED_Lip_Gloss"] = "ASA_HED_Lip_Gloss_Scalar",
            ["Hightlight1Intensity"] = "Highlight1Intensity",
            ["Hightlight2Intensity"] = "Highlight2Intensity",
            ["LightScarColor"] = "HED_Scar_Colour_Vector",
            ["LightScarColour"] = "HED_Scar_Colour_Vector",
            ["Light_Scar_Color"] = "HED_Scar_Colour_Vector",
            ["Light_Scar_Colour"] = "HED_Scar_Colour_Vector",
            ["Light_Scar_Color_Vector"] = "HED_Scar_Colour_Vector",
            ["Light_Scar_Colour_Vector"] = "HED_Scar_Colour_Vector"
        };

    private static readonly IReadOnlyDictionary<string, MetadataText> Shared =
        new Dictionary<string, MetadataText>(StringComparer.OrdinalIgnoreCase)
        {
            ["Afro"] = new("Afro", "Afro"),
            ["ALN_HED_Brows_Up_MDL_LOD0"] = new("Brows  Up", "Likely unused/broken · best guess approximation"),
            ["ALN_HED_Cheeks_Wide_MDL_LOD0"] = new("Cheeks  Wide", "Likely unused/broken · best guess approximation"),
            ["ALN_HED_Diff"] = new("Eye Diffuse Texture", "ALN_HED_Diff"),
            ["ALN_HED_Diff_Tint_Muzzle"] = new("Muzzle Colour", "ALN_HED_Diff_Tint_Muzzle"),
            ["ALN_HED_Diff_Tint_Muzzle2"] = new("Secondary Muzzle Colour", "ALN_HED_Diff_Tint_Muzzle2"),
            ["ALN_HED_Diff_Tint_Teeth"] = new("Teeth / Bone Colour", "ALN_HED_Diff_Tint_Teeth"),
            ["ALN_HED_Eyes_Close_MDL_LOD0"] = new("Eyes  Close", "Likely unused/broken · best guess approximation"),
            ["ALN_HED_Eyes_Sunken_MDL_LOD0"] = new("Eyes  Sunken", "Likely unused/broken · best guess approximation"),
            ["ALN_HED_Eyes_Wide_MDL_LOD0"] = new("Eyes  Wide", "Likely unused/broken · best guess approximation"),
            ["ALN_HED_Jaw_Thin_MDL_LOD0"] = new("Jaw  Thin", "Likely unused/broken · best guess approximation"),
            ["ALN_HED_Jaw_Wide_MDL_LOD0"] = new("Jaw  Wide", "Likely unused/broken · best guess approximation"),
            ["ALN_HED_Mouth_Down_MDL_LOD0"] = new("Mouth  Down", "Likely unused/broken · best guess approximation"),
            ["ALN_HED_Mouth_Thin_MDL_LOD0"] = new("Mouth  Thin", "Likely unused/broken · best guess approximation"),
            ["ALN_HED_Mouth_Up_MDL_LOD0"] = new("Mouth  Up", "Likely unused/broken · best guess approximation"),
            ["ALN_HED_Mouth_Wide_MDL_LOD0"] = new("Mouth  Wide", "Likely unused/broken · best guess approximation"),
            ["ALN_HED_Norm"] = new("Normal Texture", "ALN_HED_Norm"),
            ["ALN_HED_Nose_Fat_Tip_MDL_LOD0"] = new("Nose  Fat  Tip", "Likely unused/broken · best guess approximation"),
            ["ALN_HED_Nose_High_MDL_LOD0"] = new("Nose  High", "Likely unused/broken · best guess approximation"),
            ["ALN_HED_Nose_Thin_MDL_LOD0"] = new("Nose  Thin", "Likely unused/broken · best guess approximation"),
            ["ALN_HED_Nose_Wide_MDL_LOD0"] = new("Nose  Wide", "Likely unused/broken · best guess approximation"),
            ["ALN_HED_Spec_Colour"] = new("Specular Colour", "ALN_HED_Spec_Colour"),
            ["ALN_HED_Spike_Close_MDL_LOD0"] = new("Spike  Close", "Likely unused/broken · best guess approximation"),
            ["ALN_HED_Spike_Wide_MDL_LOD0"] = new("Spike  Wide", "Likely unused/broken · best guess approximation"),
            ["ALN_HED_Spwr_Muzzle_Scalar"] = new("Muzzle Specular Power", "ALN_HED_Spwr_Muzzle_Scalar"),
            ["ALN_HED_Spwr_Skin_Scalar"] = new("Skin Specular Power", "ALN_HED_Spwr_Skin_Scalar"),
            ["ALN_HED_Tatt"] = new("Tattoo Texture", "ALN_HED_Tatt"),
            ["ALN_HED_Tint"] = new("Region Mask", "ALN_HED_Tint · Red = Skin / Green = Secondary Muzzle / Blue = Muzzle"),
            ["Anderson"] = new("Anderson", "Anderson"),
            ["ASA_HED_Addn"] = new("Complexion Texture", "ASA_HED_Addn"),
            ["ASA_HED_Addn_Colour"] = new("Complexion Colour", "ASA_HED_Addn_Colour"),
            ["ASA_HED_Addn_Colour_Scalar"] = new("Complexion Colour Strength", "ASA_HED_Addn_Colour_Scalar"),
            ["ASA_HED_Addn_Mask_Scalar"] = new("Complexion Mask Alpha", "ASA_HED_Addn_Mask_Scalar"),
            ["ASA_HED_Addn_Mask_Vector"] = new("Complexion Mask Channels", "ASA_HED_Addn_Mask_Vector"),
            ["ASA_HED_Diff"] = new("Diffuse Texture", "ASA_HED_Diff"),
            ["ASA_HED_Diffuse_02_Colour"] = new("Secondary Skin Colour", "ASA_HED_Diffuse_02_Colour"),
            ["ASA_HED_Diffuse_02_Colour_Scalar"] = new("Secondary Skin Blend", "ASA_HED_Diffuse_02_Colour_Scalar"),
            ["ASA_HED_Face_Fresnel_Scalar"] = new("Face Fresnel Strength", "ASA_HED_Face_Fresnel_Scalar"),
            ["ASA_HED_Lip_Gloss_Scalar"] = new("Lip Gloss", "ASA_HED_Lip_Gloss_Scalar"),
            ["ASA_HED_MakeUp"] = new("Makeup Texture", "ASA_HED_MakeUp"),
            ["ASA_HED_Makeup_Blender_Vector"] = new("Makeup Region", "ASA_HED_Makeup_Blender_Vector · Red = Lipstick / Green = Eyeshadow / Blue = Teeth"),
            ["ASA_HED_MakeUp_Eyes"] = new("Eyeshadow Colour", "ASA_HED_MakeUp_Eyes"),
            ["ASA_HED_MakeUp_Lips"] = new("Lipstick Colour", "ASA_HED_MakeUp_Lips"),
            ["ASA_HED_MakeUp_Switch_Scalar"] = new("Makeup Strength", "ASA_HED_MakeUp_Switch_Scalar"),
            ["ASA_HED_Mask"] = new("Mask Texture", "ASA_HED_Mask"),
            ["ASA_HED_Norm"] = new("Normal Texture", "ASA_HED_Norm"),
            ["ASA_HED_Spec_Add"] = new("Specular Addition Colour", "ASA_HED_Spec_Add"),
            ["ASA_HED_SPwr_Add_Scalar"] = new("Specular Power Addition", "ASA_HED_SPwr_Add_Scalar"),
            ["ASA_HED_SPwr_Multiplier_Scalar"] = new("Specular Power Multiplier", "ASA_HED_SPwr_Multiplier_Scalar"),
            ["ASA_HED_Tatt"] = new("Tattoo Texture", "ASA_HED_Tatt"),
            ["ASA_HED_Tatt_01"] = new("Tattoo 1 Pattern Channels", "ASA_HED_Tatt_01 · Selects the RGB channel to pull from the Tattoo Texture"),
            ["ASA_HED_Tatt_01_Scalar"] = new("Tattoo 1 Region Alpha", "ASA_HED_Tatt_01_Scalar"),
            ["ASA_HED_Tatt_01_Vector"] = new("Tattoo 1 Region Channels", "ASA_HED_Tatt_01_Vector · Selects the area to use from the Mask Texture"),
            ["ASA_HED_Tatt_02"] = new("Tattoo 2 Pattern Channels", "ASA_HED_Tatt_02  · Selects the RGB channel to pull from the Tattoo Texture"),
            ["ASA_HED_Tatt_02_Scalar"] = new("Tattoo 2 Region Alpha", "ASA_HED_Tatt_02_Scalar"),
            ["ASA_HED_Tatt_02_Vector"] = new("Tattoo 2 Region Channels", "ASA_HED_Tatt_02_Vector · Selects the area to use from the Mask Texture"),
            ["ASA_HED_Tatt_Blender_Scalar"] = new("Tattoo Blend", "ASA_HED_Tatt_Blender_Scalar"),
            ["ASA_HED_Tatt_Colour"] = new("Tattoo Colour", "ASA_HED_Tatt_Colour"),
            ["ASA_HED_TClr_Tint"] = new("Transmission Colour", "ASA_HED_TClr_Tint"),
            ["ASA_HED_Teeth_Colour_Vector"] = new("Teeth Colour", "ASA_HED_Teeth_Colour_Vector"),
            ["ASA_HED_TMis_Switch"] = new("Transmission Strength", "ASA_HED_TMis_Switch"),
            ["Ashley"] = new("Ashley · Head", "Ashley"),
            ["averageHead"] = new("Average Head", "averageHead"),
            ["back head"] = new("Rear Profile", "back head"),
            ["baseHead"] = new("Base Head", "baseHead"),
            ["BAT_HED_Addn"] = new("Complexion Texture", "BAT_HED_Addn"),
            ["BAT_HED_Addn_Colour_Scalar"] = new("Complexion Strength", "BAT_HED_Addn_Colour_Scalar"),
            ["BAT_HED_Addn_Colour_Vector"] = new("Complexion Colour", "BAT_HED_Addn_Colour_Vector"),
            ["BAT_HED_Addn_Diffuse_Blend_Scalar"] = new("Complexion Diffuse Blend", "BAT_HED_Addn_Diffuse_Blend_Scalar"),
            ["BAT_HED_Addn_Spec_Vector"] = new("Complexion Specular Colour", "BAT_HED_Addn_Spec_Vector"),
            ["BAT_HED_Diff"] = new("Diffuse Texture", "BAT_HED_Diff"),
            ["BAT_HED_Face_Grad_Scalar"] = new("Face Gradient Strength", "BAT_HED_Face_Grad_Scalar"),
            ["BAT_HED_Face_Grad_Vector"] = new("Face Gradient Colour", "BAT_HED_Face_Grad_Vector"),
            ["BAT_HED_Mask"] = new("Complexion Region Mask", "BAT_HED_Mask"),
            ["BAT_HED_Mask_Vector"] = new("Complexion Mask Channels", "BAT_HED_Mask_Vector · Red = Upper Face / Green = Lower Face + Neck / Blue = Cranium + Scalp"),
            ["BAT_HED_Neck_Grad_Scalar"] = new("Neck Gradient Strength", "BAT_HED_Neck_Grad_Scalar"),
            ["BAT_HED_Neck_Grad_Vector"] = new("Neck Gradient Colour", "BAT_HED_Neck_Grad_Vector"),
            ["BAT_HED_Norm"] = new("Normal Texture", "BAT_HED_Norm"),
            ["BAT_HED_Spec"] = new("Specular Texture", "BAT_HED_Spec · Blue channel masks the teeth for colouring"),
            ["BAT_HED_SPwr_Scalar"] = new("Specular Power", "BAT_HED_SPwr_Scalar · Only present in LE1"),
            ["BAT_HED_Teeth_Vector"] = new("Teeth Colour", "BAT_HED_Teeth_Vector"),
            ["BAT_HED_Tint"] = new("Tint Texture", "BAT_HED_Tint · Red = Face / Green = Chin / Blue = Cranium"),
            ["BAT_HED_Tmis_Scalar"] = new("Transmission Strength", "BAT_HED_Tmis_Scalar"),
            ["BAT_HED_TopHead_Grad_Scalar"] = new("Top Head Gradient Strength", "BAT_HED_TopHead_Grad_Scalar"),
            ["BAT_HED_TopHead_Grad_Vector"] = new("Top Head Gradient Colour", "BAT_HED_TopHead_Grad_Vector"),
            ["blonde"] = new("Secondary Addition Colour", "blonde"),
            ["Blowout_Scalar"] = new("Diffuse Gain", "Blowout_Scalar · LE2 clamps this value to 1"),
            ["BONE_blinkFix"] = new("Blink Fix", "BONE_blinkFix"),
            ["brow_Back"] = new("Brows Back", "brow_Back"),
            ["brow_Down"] = new("Brows Down", "brow_Down"),
            ["brow_Forward"] = new("Brows Forward", "brow_Forward"),
            ["brow_Up"] = new("Brows Up", "brow_Up"),
            ["BuzzCut"] = new("Buzz Cut", "BuzzCut"),
            ["BuzzCut_WidowsPeak"] = new("Buzz Cut · Widow's Peak", "BuzzCut_WidowsPeak"),
            ["cheek_back"] = new("Cheeks Back", "cheek_back"),
            ["cheek_BonesIn"] = new("Cheeks Bones In", "cheek_BonesIn"),
            ["cheek_BonesOut"] = new("Cheeks Bones Out", "cheek_BonesOut"),
            ["cheek_DepthBack"] = new("Cheeks Depth Back", "cheek_DepthBack"),
            ["cheek_DepthFront"] = new("Cheeks Depth Front", "cheek_DepthFront"),
            ["cheek_Forward"] = new("Cheeks Forward", "cheek_Forward"),
            ["cheek_Gaunt"] = new("Cheeks Gaunt", "cheek_Gaunt"),
            ["cheek_up"] = new("Cheeks Up", "cheek_up"),
            ["cheeks_Back"] = new("Cheeks Back", "cheeks_Back"),
            ["cheeks_Down"] = new("Cheeks Down", "cheeks_Down"),
            ["cheeks_Forward"] = new("Cheeks Forward", "cheeks_Forward"),
            ["cheeks_gaunt"] = new("Cheeks Gaunt", "cheeks_gaunt · Unused"),
            ["cheeks_Narrow"] = new("Cheeks Narrow", "cheeks_Narrow"),
            ["cheeks_Up"] = new("Cheeks Up", "cheeks_Up"),
            ["cheeks_Wide"] = new("Cheeks Wide", "cheeks_Wide"),
            ["CubeMap_Intensity"] = new("Eye Reflection Strength", "CubeMap_Intensity - LE3 Only"),
            ["DEBUG_capCorrector"] = new("Scalp Cap Corrector", "DEBUG_capCorrector"),
            ["DEBUG_EyeLidCorrector"] = new("Eyelid Corrector", "DEBUG_EyeLidCorrector"),
            ["DEBUG_InnerEyeCorrector"] = new("Inner Eye Corrector", "DEBUG_InnerEyeCorrector"),
            ["deiter"] = new("Deiter", "deiter"),
            ["ears_down"] = new("Ears Down", "ears_down"),
            ["ears_In"] = new("Ears In", "ears_In"),
            ["ears_large"] = new("Ears Large", "ears_large"),
            ["ears_Out"] = new("Ears Out", "ears_Out"),
            ["ears_small"] = new("Ears Small", "ears_small"),
            ["ears_up"] = new("Ears Up", "ears_up"),
            ["Eastwood"] = new("Eastwood", "Eastwood"),
            ["Emis_Color"] = new("Eye Emissive Colour", "Emis_Color · Used for TIM Eyes / Renegade Scars"),
            ["Emis_Scalar"] = new("Eye Emissive Strength", "Emis_Scalar · Used for TIM Eyes / Renegade Scars"),
            ["EYE_Diff"] = new("Eye Diffuse Texture", "EYE_Diff"),
            ["EYE_Glow"] = new("Eye Glow Colour", "EYE_Glow"),
            ["EYE_Glow_Intensity"] = new("Eye Glow Intensity", "EYE_Glow_Intensity"),
            ["EYE_Iris_Colour_Vector"] = new("Iris Colour", "EYE_Iris_Colour_Vector"),
            ["EYE_Iris_Norm"] = new("Iris Normal Texture", "EYE_Iris_Norm"),
            ["EYE_Lens_Norm"] = new("Lens Normal Texture", "EYE_Lens_Norm"),
            ["EYE_Mask"] = new("Eye Mask / Specular Texture", "EYE_Mask"),
            ["Eye_Norm"] = new("Eye Normal Texture", "Eye_Norm"),
            ["Eye_Pupil"] = new("Pupil Scale", "Eye_Pupil"),
            ["eye_Shape_droop"] = new("Shape Droop", "eye_Shape_droop"),
            ["EYE_Spec"] = new("Eye Specular Strength", "EYE_Spec"),
            ["EYE_Spec_Power"] = new("Eye Specular Power", "EYE_Spec_Power · LE3 Only"),
            ["Eye_Specular"] = new("Eye Specular Strength", "Eye_Specular · LE3 Only"),
            ["EYE_Tint"] = new("Eye Tint", "EYE_Tint"),
            ["EYE_Tint_Iris"] = new("Iris Colour", "EYE_Tint_Iris"),
            ["EYE_White_Colour_Vector"] = new("Sclera Colour", "EYE_White_Colour_Vector"),
            ["EyeLightScattering"] = new("Eye Light Scattering", "EyeLightScattering"),
            ["eyes_ashleyShape"] = new("Ashley Shape", "eyes_ashleyShape"),
            ["eyes_Back"] = new("Eyes Back", "eyes_Back"),
            ["eyes_bagOut"] = new("Bag Out", "eyes_bagOut · Unused"),
            ["eyes_bagsIn"] = new("Eye Bags In", "eyes_bagsIn"),
            ["eyes_bagsOut"] = new("Eye Bags Out", "eyes_bagsOut"),
            ["eyes_BallBack"] = new("Eyeballs Back", "eyes_BallBack"),
            ["eyes_BallDown"] = new("Eyeballs Down", "eyes_BallDown"),
            ["eyes_BallForward"] = new("Eyeballs Forward", "eyes_BallForward"),
            ["eyes_BallUp"] = new("Eyeballs Up", "eyes_BallUp"),
            ["eyes_Big"] = new("Eyes Large", "eyes_Big"),
            ["eyes_browBack"] = new("Brows Back", "eyes_browBack"),
            ["eyes_browDown"] = new("Brows Down", "eyes_browDown"),
            ["eyes_browForward"] = new("Brows Forward", "eyes_browForward"),
            ["eyes_browUp"] = new("Brows Up", "eyes_browUp"),
            ["eyes_Down"] = new("Eyes Down", "eyes_Down"),
            ["eyes_Forward"] = new("Eyes Forward", "eyes_Forward"),
            ["eyes_Large"] = new("Eyes Large", "eyes_Large"),
            ["eyes_lashAngle"] = new("Lash Angle", "eyes_lashAngle · Unused"),
            ["eyes_lashLength"] = new("Lash Length", "eyes_lashLength · Unused"),
            ["eyes_LidLower"] = new("Eyelid Lower", "eyes_LidLower"),
            ["eyes_LidUpper"] = new("Eyelid Upper", "eyes_LidUpper"),
            ["eyes_Narow"] = new("Eye Shape Narrow", "eyes_Narow"),
            ["eyes_narrow"] = new("Eyes Narrow", "eyes_narrow"),
            ["eyes_PosDown"] = new("Eyes Down", "eyes_PosDown"),
            ["eyes_PosUp"] = new("Eyes Up", "eyes_PosUp"),
            ["eyes_RotateIn"] = new("Eyeballs Narrow", "eyes_RotateIn"),
            ["eyes_RotateOut"] = new("Eyeballs Wide", "eyes_RotateOut"),
            ["eyes_Shape_droop"] = new("Shape Droop", "eyes_Shape_droop"),
            ["eyes_Shape_flatTop"] = new("Shape Flat Top", "eyes_Shape_flatTop"),
            ["eyes_Shape_outerPoint"] = new("Shape Outer Point", "eyes_Shape_outerPoint"),
            ["eyes_Shape_sleepy"] = new("Shape Sleepy", "eyes_Shape_sleepy"),
            ["eyes_Shape_squint"] = new("Shape Squint", "eyes_Shape_squint"),
            ["eyes_Shape_wide"] = new("Shape Wide", "eyes_Shape_wide"),
            ["eyes_SlantDown"] = new("Eye Corners Down", "eyes_SlantDown"),
            ["eyes_SlantUp"] = new("Eye Corners Up", "eyes_SlantUp"),
            ["eyes_small"] = new("Eyes Small", "eyes_small"),
            ["eyes_socketShift"] = new("Socket Shift", "eyes_socketShift"),
            ["eyes_Up"] = new("Eyes Up", "eyes_Up"),
            ["eyes_Wide"] = new("Eyes Wide", "eyes_Wide"),
            ["eyeShape_Ashley"] = new("Ashley", "eyeShape_Ashley"),
            ["eyeShape_droop"] = new("Droop", "eyeShape_droop"),
            ["eyeShape_flatTop"] = new("Eye Shape Flat Top", "eyeShape_flatTop"),
            ["eyeShape_highInside"] = new("Eye Shape High Inner Corner", "eyeShape_highInside"),
            ["eyeShape_iconic"] = new("Iconic Shepard", "eyeShape_iconic"),
            ["eyeShape_liara"] = new("Liara", "eyeShape_liara"),
            ["eyeShape_oldBlk"] = new("Black · Old", "eyeShape_oldBlk"),
            ["eyeShape_SlantUp"] = new("Eye Shape Slant Up", "eyeShape_SlantUp"),
            ["eyeShape_sleepy"] = new("Eye Shape Sleepy", "eyeShape_sleepy"),
            ["eyeShape_wide"] = new("Eye Shape Wide", "eyeShape_wide"),
            ["eyeShape_yngAsn"] = new("Asian · Young", "eyeShape_yngAsn"),
            ["face_thin"] = new("Face Thin", "face_thin"),
            ["flatTop"] = new("Flat Top", "flatTop"),
            ["flatTop_WidowsPeak"] = new("Flat Top · Widow's Peak", "flatTop_WidowsPeak"),
            ["foreHead_In"] = new("Forehead In", "foreHead_In"),
            ["foreHead_Out"] = new("Forehead Out", "foreHead_Out"),
            ["Formal"] = new("Formal", "Formal · Unused"),
            ["Geezer"] = new("Geezer", "Geezer"),
            ["HAIR_ADDN_Diff"] = new("Hair Diffuse Texture", "HAIR_ADDN_Diff  · LE3 Version. Red = Highlights"),
            ["HAIR_centerPart"] = new("Centre Part", "HAIR_centerPart"),
            ["HAIR_Diff"] = new("Hair Diffuse Texture", "HAIR_Diff"),
            ["HAIR_Mask"] = new("Hair Mask Texture", "HAIR_Mask"),
            ["HAIR_Mask_Alpha_Scalar"] = new("Mask Alpha", "HAIR_Mask_Alpha_Scalar"),
            ["HAIR_Norm"] = new("Hair Normal Texture", "HAIR_Norm"),
            ["HAIR_pulledBackBig"] = new("Pulled Back · Full", "HAIR_pulledBackBig"),
            ["HAIR_pulledBackSlick"] = new("Pulled Back · Slick", "HAIR_pulledBackSlick"),
            ["HAIR_Shine_Desaturate_Scalar"] = new("Shine Desaturate", "HAIR_Shine_Desaturate_Scalar"),
            ["HAIR_sidePart"] = new("Side Part", "HAIR_sidePart"),
            ["HAIR_slickWidowsPeak"] = new("Slick Widow's Peak", "HAIR_slickWidowsPeak"),
            ["Hair_Spec_Aniso_Exp_Scalar"] = new("Hair Anisotropic Specular Strength", "Hair_Spec_Aniso_Exp_Scalar - LE1 only. Unused but retained for material round-tripping"),
            ["HAIR_Spec_Contribution_Scalar"] = new("Hair Specular Strength", "HAIR_Spec_Contribution_Scalar"),
            ["HAIR_SpecShift"] = new("Primary Hair Specular Shift Texture", "HAIR_SpecShift"),
            ["HAIR_SpecShift2"] = new("Secondary Hair Specular Shift Texture", "HAIR_SpecShift2"),
            ["HAIR_splitSide"] = new("Split Side", "HAIR_splitSide"),
            ["HAIR_splitSide\""] = new("Split Side\"", "HAIR_splitSide\" · Unused"),
            ["HAIR_Tang"] = new("Hair Tangent Texture", "HAIR_Tang"),
            ["head_ScaleUp"] = new("Head Scale Up", "head_ScaleUp"),
            ["head_thin"] = new("Outer Plates · Thin", "head_thin"),
            ["headSpikes_Long"] = new("Head Spikes Long", "headSpikes_Long"),
            ["headSpikes_Short"] = new("Head Spikes Short", "headSpikes_Short"),
            ["HED_Addn"] = new("Facial Hair / Addition Texture", "HED_Addn"),
            ["HED_Addn_Add_Scalar"] = new("Addition Additive Blend", "HED_Addn_Add_Scalar"),
            ["HED_Addn_Blend_Scalar"] = new("Addition Normal Strength", "HED_Addn_Blend_Scalar"),
            ["HED_Addn_Blowout_Scalar"] = new("Primary Addition Colour Strength", "HED_Addn_Blowout_Scalar"),
            ["HED_Addn_Colour_02_Scalar"] = new("Secondary Addition Colour Strength", "HED_Addn_Colour_02_Scalar"),
            ["HED_Addn_Colour_Vector"] = new("Primary Addition Colour", "HED_Addn_Colour_Vector"),
            ["HED_Addn_Multiply_Scalar"] = new("Addition Multiplicative Blend", "HED_Addn_Multiply_Scalar"),
            ["HED_Addn_Spec_Add_Scalar"] = new("Addition Specular Colour Strength", "HED_Addn_Spec_Add_Scalar"),
            ["HED_Addn_Spec_Lips_Scalar"] = new("Addition Lips Specular", "HED_Addn_Spec_Lips_Scalar"),
            ["HED_Addn_SPwr_Add_Scalar"] = new("Addition Specular Power", "HED_Addn_SPwr_Add_Scalar"),
            ["HED_Addn_SPwr_Lips_Scalar"] = new("Addition Lips Specular Power", "HED_Addn_SPwr_Lips_Scalar · HMF lip-region Phong exponent recovered from the direct-light permutation."),
            ["HED_Blush_Scalar"] = new("Blush Strength", "HED_Blush_Scalar"),
            ["HED_Blush_Vector"] = new("Blush Colour", "HED_Blush_Vector"),
            ["HED_Brow"] = new("Brow Texture", "HED_Brow · Player material only"),
            ["HED_Brow_FadeOut_Scalar"] = new("Brow Fade Out", "HED_Brow_FadeOut_Scalar"),
            ["HED_Brow_Tint_Scalar"] = new("Brow Tint", "HED_Brow_Tint_Scalar"),
            ["HED_Brow_Tint_Vector"] = new("Brow Tint Colour", "HED_Brow_Tint_Vector"),
            ["HED_Custom_Scar_Scalar"] = new("Scar Normal Strength", "HED_Custom_Scar_Scalar"),
            ["HED_Diff"] = new("Face Diffuse Texture", "HED_Diff"),
            ["HED_EYE_FX_Scalar"] = new("Eye Effects Strength", "HED_EYE_FX_Scalar"),
            ["HED_EYE_FX_Vector"] = new("Eye Effects Colour", "HED_EYE_FX_Vector"),
            ["HED_EyeShadow_Tint_Scalar"] = new("Eye Shadow Tint", "HED_EyeShadow_Tint_Scalar"),
            ["HED_EyeShadow_Tint_Vector"] = new("Eye Shadow Tint Colour", "HED_EyeShadow_Tint_Vector"),
            ["HED_Frek"] = new("Freckles Texture", "HED_Frek"),
            ["HED_Frek_BlueChannel_Scalar"] = new("Freckles Blue Channel", "HED_Frek_BlueChannel_Scalar"),
            ["HED_Frek_BlueChannel_Vector"] = new("Freckles Blue Channel Colour", "HED_Frek_BlueChannel_Vector"),
            ["HED_Frek_GreenChannel_Scalar"] = new("Freckles Green Channel", "HED_Frek_GreenChannel_Scalar"),
            ["HED_Frek_GreenChannel_Vector"] = new("Freckles Green Channel Colour", "HED_Frek_GreenChannel_Vector"),
            ["HED_Frek_RedChannel_Scalar"] = new("Freckles Red Channel", "HED_Frek_RedChannel_Scalar"),
            ["HED_Frek_RedChannel_Vector"] = new("Freckles Red Channel Colour", "HED_Frek_RedChannel_Vector"),
            ["HED_Hair_Colour_Vector"] = new("Hair Colour", "HED_Hair_Colour_Vector"),
            ["HED_Lash_Diff"] = new("Eyelash Diffuse", "HED_Lash_Diff"),
            ["HED_Lash_Diff_Vector"] = new("Eyelash Colour", "HED_Lash_Diff_Vector"),
            ["HED_Lash_Opac_Scalar"] = new("Eyelash Opacity", "HED_Lash_Opac_Scalar"),
            ["HED_Lash_Spec_Scalar"] = new("Eyelash Specular", "HED_Lash_Spec_Scalar"),
            ["HED_Lips_Tint_Scalar"] = new("Lips Tint Strength", "HED_Lips_Tint_Scalar"),
            ["HED_Lips_Tint_Vector"] = new("Lip Tint Colour", "HED_Lips_Tint_Vector"),
            ["HED_Makeup_Mask"] = new("Makeup Mask Texture", "HED_Makeup_Mask · Red = Eyeshadow / Green = Mascara/Lipstick / Blue = Lipstick Selector / Alpha = Blush/Lipstick"),
            ["HED_Mask"] = new("Face Mask Texture", "HED_Mask · Masks regions for brows/beard additions"),
            ["HED_Mask_Scalar"] = new("Face Mask Alpha Strength", "HED_Mask_Scalar"),
            ["HED_Mask_Vector"] = new("Face Mask Channel Weights", "HED_Mask_Vector"),
            ["HED_Norm"] = new("Face Normal Texture", "HED_Norm"),
            ["HED_Norm_02"] = new("Secondary Face Normal Texture", "HED_Norm_02"),
            ["HED_Norm_Blend"] = new("Normal Blend", "HED_Norm_Blend"),
            ["HED_Scalp_BuzzCut_Alpha_Scalar"] = new("Scalp Buzz Cut Alpha", "HED_Scalp_BuzzCut_Alpha_Scalar"),
            ["HED_Scalp_Diff"] = new("Scalp Diffuse", "HED_Scalp_Diff"),
            ["HED_Scalp_Mask_OverlayKill_Scalar"] = new("Scalp Mask Overlay Kill", "HED_Scalp_Mask_OverlayKill_Scalar"),
            ["HED_Scalp_Mask_Scalar"] = new("Scalp Mask", "HED_Scalp_Mask_Scalar"),
            ["HED_Scalp_Norm"] = new("Scalp Normal", "HED_Scalp_Norm"),
            ["HED_Scalp_PhongSpec_Scalar"] = new("Scalp Phong Specular", "HED_Scalp_PhongSpec_Scalar"),
            ["HED_Scalp_Spec"] = new("Scalp Specular", "HED_Scalp_Spec"),
            ["HED_Scalp_SpecShift"] = new("Primary Scalp Specular Shift Texture", "HED_Scalp_SpecShift"),
            ["HED_Scalp_SpecShift2"] = new("Secondary Scalp Specular Shift Texture", "HED_Scalp_SpecShift2"),
            ["HED_Scar"] = new("Scar Texture", "HED_Scar · RGA = Normals / B = Scar Colour"),
            ["HED_Scar_Colour_Vector"] = new("Scar Emissive Color", "HED_Scar_Colour_Vector"),
            ["HED_Scar_Diffuse_Scalar"] = new("Scar Colour Strength", "HED_Scar_Diffuse_Scalar"),
            ["HED_Scar_Scalar"] = new("Scar", "HED_Scar_Scalar"),
            ["HED_Scar_Vector"] = new("Scar Colour", "HED_Scar_Vector"),
            ["HED_Spec_Add_Vector"] = new("Skin Specular Colour", "HED_Spec_Add_Vector"),
            ["HED_Spec_Aniso_Exp_Scalar"] = new("Scalp Anisotropic Specular Strength", "HED_Spec_Aniso_Exp_Scalar · Normalised anisotropic hair colour; not the tangent-lobe exponent"),
            ["HED_Spec_NoBrow"] = new("Addition Specular Suppression", "HED_Spec_NoBrow"),
            ["HED_SPwr_Scalar"] = new("Specular Power", "HED_SPwr_Scalar · LE1 Only"),
            ["HED_Tang"] = new("Scalp Tangent Texture", "HED_Tang"),
            ["HED_TClr_Vector"] = new("Skin Transmission Colour", "HED_TClr_Vector"),
            ["HED_Teeth_Diff"] = new("Teeth Texture", "HED_Teeth_Diff"),
            ["HED_Teeth_Scalar"] = new("Teeth Material Strength", "HED_Teeth_Scalar"),
            ["HED_Teeth_Vector"] = new("Teeth Colour", "HED_Teeth_Vector"),
            ["HED_TMis_Scalar"] = new("Skin Transmission Strength", "HED_TMis_Scalar"),
            ["Highlight1Color"] = new("Hair Highlight 1 Colour", "Highlight1Color"),
            ["Highlight1Colour_Specularity"] = new("Hair Highlight1 Colour Specular", "Highlight1Colour_Specularity"),
            ["Highlight1Colour_Vector"] = new("Hair Highlight1 Colour", "Highlight1Colour_Vector"),
            ["Highlight1Intensity"] = new("Hair Highlight 1 Intensity", "Highlight1Intensity"),
            ["Highlight1SpecExp_Scalar"] = new("Hair Highlight 1 Specular Exponent", "Highlight1SpecExp_Scalar"),
            ["Highlight1Specularity"] = new("Hair Highlight 1 Specular", "Highlight1Specularity"),
            ["Highlight2Color"] = new("Hair Highlight 2 Colour", "Highlight2Color"),
            ["Highlight2Colour_Specularity"] = new("Hair Highlight 2 Colour Specular", "Highlight2Colour_Specularity"),
            ["Highlight2Colour_Vector"] = new("Hair Highlight 2 Colour", "Highlight2Colour_Vector"),
            ["Highlight2Intensity"] = new("Hair Highlight 2 Intensity", "Highlight2Intensity"),
            ["Highlight2SpecExp_Scalar"] = new("Hair Highlight 2 Specular Exponent", "Highlight2SpecExp_Scalar"),
            ["Highlight2Specularity"] = new("Hair Highlight 2 Specular", "Highlight2Specularity"),
            ["HIR_Beard"] = new("Beard", "HIR_Beard"),
            ["HIR_BeardTipMorph"] = new("Beard Tip", "HIR_BeardTipMorph"),
            ["HIR_TimSelect"] = new("Moustache", "HIR_TimSelect"),
            ["Iconic"] = new("Iconic Shepard · Head", "Iconic"),
            ["Iris_Colour_Multiplier"] = new("Iris Colour Strength", "Iris_Colour_Multiplier"),
            ["Jack"] = new("Jack", "Jack"),
            ["Jacob"] = new("Jacob", "Jacob"),
            ["jaw_chinBack"] = new("Chin Back", "jaw_chinBack"),
            ["jaw_chinDown"] = new("Chin Down", "jaw_chinDown"),
            ["jaw_chinForward"] = new("Chin Forward", "jaw_chinForward"),
            ["jaw_chinIn"] = new("Chin In", "jaw_chinIn"),
            ["jaw_chinOut"] = new("Chin Out", "jaw_chinOut"),
            ["jaw_chinThin"] = new("Chin Thin", "jaw_chinThin"),
            ["jaw_chinUp"] = new("Chin Up", "jaw_chinUp"),
            ["jaw_chinWide"] = new("Chin Wide", "jaw_chinWide"),
            ["jaw_doublechin"] = new("Double Chin", "jaw_doublechin"),
            ["jaw_Forward"] = new("Jaw Forward", "jaw_Forward"),
            ["jaw_Jowls"] = new("Jowls", "jaw_Jowls"),
            ["jaw_narrow"] = new("Jaw Narrow", "jaw_narrow"),
            ["jaw_wide"] = new("Jaw Wide", "jaw_wide"),
            ["JawLower"] = new("Jaw Lower", "JawLower"),
            ["Joker"] = new("Joker", "Joker"),
            ["Kaiden"] = new("Kaidan", "Kaiden"),
            ["Kasumi"] = new("Kasumi", "Kasumi"),
            ["KRO_EYE_Diff"] = new("Eye Diffuse Texture", "KRO_EYE_Diff"),
            ["KRO_EYE_Iris_Norm"] = new("Iris Normal Texture", "KRO_EYE_Iris_Norm"),
            ["KRO_EYE_Lens_Norm"] = new("Lens Normal Texture", "KRO_EYE_Lens_Norm"),
            ["KRO_Eye_Mask"] = new("Eye and Pupil Mask", "KRO_Eye_Mask"),
            ["KRO_Eye_Spec"] = new("Eye Specular Texture", "KRO_Eye_Spec"),
            ["KRO_HED_Addn"] = new("Complexion Texture", "KRO_HED_Addn"),
            ["KRO_HED_Addn_Colour_Scalar"] = new("Complexion Strength", "KRO_HED_Addn_Colour_Scalar"),
            ["KRO_HED_Addn_Colour_Vector"] = new("Complexion Colour", "KRO_HED_Addn_Colour_Vector"),
            ["KRO_HED_Diff"] = new("Diffuse Texture", "KRO_HED_Diff"),
            ["KRO_HED_Face_Grad_Scalar"] = new("Face Gradient Strength", "KRO_HED_Face_Grad_Scalar"),
            ["KRO_HED_Face_Grad_Vector"] = new("Face Gradient Colour", "KRO_HED_Face_Grad_Vector"),
            ["KRO_HED_Helmet_Tint"] = new("Head Plate Tint", "KRO_HED_Helmet_Tint"),
            ["KRO_HED_Lips_Grad_Scalar"] = new("Lip Gradient Strength", "KRO_HED_Lips_Grad_Scalar"),
            ["KRO_HED_Lips_Grad_Vector"] = new("Lip Gradient Colour", "KRO_HED_Lips_Grad_Vector"),
            ["KRO_HED_Mask"] = new("Complexion Region Mask", "KRO_HED_Mask · Red = Brows / Green = Lower Face / Blue = Neck"),
            ["KRO_HED_Mask_Vector"] = new("Complexion Mask Channels", "KRO_HED_Mask_Vector"),
            ["KRO_HED_Norm"] = new("Normal Texture", "KRO_HED_Norm"),
            ["KRO_HED_Shell_Grad_Scalar"] = new("Head Plate Gradient Strength", "KRO_HED_Shell_Grad_Scalar"),
            ["KRO_HED_Shell_Grad_Vector"] = new("Head Plate Gradient Colour", "KRO_HED_Shell_Grad_Vector"),
            ["KRO_HED_Shell_Spec_Add"] = new("Head Plate Specular Colour", "KRO_HED_Shell_Spec_Add"),
            ["KRO_HED_Spec_Add"] = new("Skin Specular Colour", "KRO_HED_Spec_Add"),
            ["KRO_HED_Spec_Scalar"] = new("Specular Strength", "KRO_HED_Spec_Scalar"),
            ["KRO_HED_SPwr_Scalar"] = new("Specular Power", "KRO_HED_SPwr_Scalar"),
            ["KRO_HED_Teeth_Vector"] = new("Teeth Colour", "KRO_HED_Teeth_Vector"),
            ["KRO_HED_Tint"] = new("Tint Texture", "KRO_HED_Tint · Red = Head Plates / Green =  Skin / Blue = Teeth"),
            ["KRO_HED_Tmis_Scalar"] = new("Transmission Strength", "KRO_HED_Tmis_Scalar"),
            ["KRO_HED_Tnt2"] = new("Gradient Texture", "KRO_HED_Tnt2 · Red = Head Plates / Green = Skin / Blue = Lips"),
            ["Krogan_Pupil"] = new("Pupil Scale", "Krogan_Pupil"),
            ["lashes"] = new("Lashes", "lashes"),
            ["mandible_extend"] = new("Mandibles Extend", "mandible_extend"),
            ["mandible_Flare"] = new("Mandibles Flare", "mandible_Flare"),
            ["mandible_long"] = new("Mandibles Long", "mandible_long"),
            ["mandible_retract"] = new("Mandibles Retract", "mandible_retract"),
            ["mandible_Rotate"] = new("Mandibles Rotate", "mandible_Rotate"),
            ["mandible_short"] = new("Mandibles Short", "mandible_short"),
            ["mandible_Thick"] = new("Mandibles Thick", "mandible_Thick"),
            ["Mask"] = new("Teeth Opacity", "Mask · Any value below 0.33 will hide the teeth"),
            ["Miranda"] = new("Miranda", "Miranda"),
            ["mouth_Back"] = new("Mouth Back", "mouth_Back"),
            ["mouth_cheekMass"] = new("Cheeks Mass", "mouth_cheekMass"),
            ["mouth_CornersDown"] = new("Mouth Corners Down", "mouth_CornersDown"),
            ["mouth_CornersUp"] = new("Mouth Corners Up", "mouth_CornersUp"),
            ["mouth_Down"] = new("Mouth Down", "mouth_Down"),
            ["mouth_Forward"] = new("Mouth Forward", "mouth_Forward"),
            ["mouth_jawBack"] = new("Jaw Back", "mouth_jawBack"),
            ["mouth_jawForward"] = new("Jaw Forward", "mouth_jawForward"),
            ["mouth_jawLower"] = new("Jaw Lower", "mouth_jawLower"),
            ["mouth_jawRaise"] = new("Jaw Raise", "mouth_jawRaise"),
            ["mouth_lipsFat"] = new("Lips Full", "mouth_lipsFat"),
            ["mouth_lipsForward"] = new("Lips Forward", "mouth_lipsForward"),
            ["mouth_lipsLarge"] = new("Lips Large", "mouth_lipsLarge"),
            ["mouth_lipsSmall"] = new("Lips Small", "mouth_lipsSmall"),
            ["mouth_lipsThin"] = new("Lips Thin", "mouth_lipsThin"),
            ["mouth_LowerLipFat"] = new("Lower Lip Full", "mouth_LowerLipFat"),
            ["mouth_lowerLipUp"] = new("Mouth Lower Lip Up", "mouth_lowerLipUp"),
            ["mouth_Narrow"] = new("Mouth Narrow", "mouth_Narrow"),
            ["mouth_overBite"] = new("Mouth Overbite", "mouth_overBite"),
            ["mouth_underBite"] = new("Mouth Underbite", "mouth_underBite"),
            ["mouth_Up"] = new("Mouth Up", "mouth_Up"),
            ["mouth_UpperLip"] = new("Mouth Upper Lip", "mouth_UpperLip"),
            ["mouth_upperLipDown"] = new("Mouth Upper Lip Down", "mouth_upperLipDown"),
            ["mouth_upperLipFat"] = new("Upper Lip Full", "mouth_upperLipFat"),
            ["mouth_Wide"] = new("Mouth Wide", "mouth_Wide"),
            ["mouthSackNarrow"] = new("Mouth Sack Narrow", "mouthSackNarrow"),
            ["mouthShape_ashley"] = new("Ashley", "mouthShape_ashley"),
            ["mouthShape_centerKleft"] = new("Mouth Centre Cleft", "mouthShape_centerKleft"),
            ["MouthShape_Diddy"] = new("Mouth Diddy", "MouthShape_Diddy"),
            ["mouthShape_fatLips"] = new("Lip Shape Full", "mouthShape_fatLips"),
            ["mouthShape_iconic"] = new("Iconic Shepard", "mouthShape_iconic"),
            ["mouthShape_liara"] = new("Liara", "mouthShape_liara"),
            ["mouthShape_oldAsn"] = new("Asian · Old", "mouthShape_oldAsn"),
            ["mouthShape_oldBlk"] = new("Black · Old", "mouthShape_oldBlk"),
            ["mouthShape_oldCauc"] = new("Caucasian · Old", "mouthShape_oldCauc"),
            ["mouthShape_overBite"] = new("Lips Overbite", "mouthShape_overBite"),
            ["mouthShape_Philtrum"] = new("Mouth Philtrum", "mouthShape_Philtrum"),
            ["mouthShape_pinchedSides"] = new("Mouth Pinched Sides", "mouthShape_pinchedSides"),
            ["mouthShape_thin"] = new("Mouth Thin", "mouthShape_thin"),
            ["mouthShape_underBite"] = new("Lips Underbite", "mouthShape_underBite"),
            ["mouthShape_yngAsn"] = new("Asian · Young", "mouthShape_yngAsn"),
            ["mouthShape_yngBlk"] = new("Black · Young", "mouthShape_yngBlk"),
            ["mouthShape_yngCauc"] = new("Caucasian · Young", "mouthShape_yngCauc"),
            ["neck_apple"] = new("Adam's Apple", "neck_apple"),
            ["neck_correction"] = new("Correction", "neck_correction"),
            ["neck_thick"] = new("Neck Thick", "neck_thick · Unused"),
            ["neck_Thin"] = new("Neck Thin", "neck_Thin"),
            ["neck_wide"] = new("Neck Wide", "neck_wide"),
            ["None"] = new("None", "None · Unused"),
            ["nose_BendLeft"] = new("Nose Bend Left", "nose_BendLeft"),
            ["nose_BendRight"] = new("Nose Bend Right", "nose_BendRight"),
            ["nose_BottomIn"] = new("Nose Bottom In", "nose_BottomIn"),
            ["nose_BottomOut"] = new("Nose Bottom Out", "nose_BottomOut"),
            ["nose_BottomThin"] = new("Bottom Thin", "nose_BottomThin · Unused"),
            ["nose_BottomWide"] = new("Bottom Wide", "nose_BottomWide · Unused"),
            ["nose_BridgeIn"] = new("Bridge In", "nose_BridgeIn"),
            ["nose_BridgeNarrow"] = new("Nose Bridge Narrow", "nose_BridgeNarrow"),
            ["nose_BridgeOut"] = new("Bridge Out", "nose_BridgeOut"),
            ["nose_BridgeThin"] = new("Bridge Thin", "nose_BridgeThin"),
            ["nose_BridgeWide"] = new("Bridge Wide", "nose_BridgeWide"),
            ["nose_Down"] = new("Nose Down", "nose_Down"),
            ["nose_In"] = new("Nose In", "nose_In"),
            ["nose_Long"] = new("Nose Long", "nose_Long"),
            ["nose_Narrow"] = new("Nose Narrow", "nose_Narrow"),
            ["nose_nostrilsnarrow"] = new("Nostrils Narrow", "nose_nostrilsnarrow"),
            ["nose_nostrilsWide"] = new("Nostrils Wide", "nose_nostrilsWide"),
            ["nose_Out"] = new("Nose Out", "nose_Out"),
            ["nose_Short"] = new("Nose Short", "nose_Short"),
            ["nose_TipDown"] = new("Tip Down", "nose_TipDown"),
            ["nose_tipIn"] = new("Tip In", "nose_tipIn"),
            ["nose_tipNarrow"] = new("Tip Narrow", "nose_tipNarrow"),
            ["nose_TipUp"] = new("Tip Up", "nose_TipUp"),
            ["nose_tipWide"] = new("Tip Wide", "nose_tipWide"),
            ["nose_topIn"] = new("Nose Top In", "nose_topIn"),
            ["nose_topOut"] = new("Nose Top Out", "nose_topOut"),
            ["nose_Up"] = new("Nose Up", "nose_Up"),
            ["nose_Wide"] = new("Nose Wide", "nose_Wide"),
            ["objobjWillis"] = new("Willis Variant", "objobjWillis"),
            ["Primary_Reflection_Multiplier"] = new("Primary Reflection Strength", "Primary_Reflection_Multiplier"),
            ["pupil_Large"] = new("Pupil Large (Vestigial)", "pupil_Large · Unused - it affects the lower jaw rather than pupil size and has almost no visible effect"),
            ["pupil_Small"] = new("Pupil Size", "pupil_Small · Unused"),
            ["race_Ashley"] = new("Ashley · Blend", "race_Ashley"),
            ["race_asnOld"] = new("Asian Old", "race_asnOld · Unused"),
            ["race_asnYoung"] = new("Asian Young", "race_asnYoung · Unused"),
            ["race_blackOld"] = new("Black Old", "race_blackOld"),
            ["race_Blackyng"] = new("Blackyng", "race_Blackyng"),
            ["race_cauOld"] = new("Cau Old", "race_cauOld"),
            ["race_cauYng"] = new("Cau Yng", "race_cauYng"),
            ["race_iconic"] = new("Iconic", "race_iconic · Unused"),
            ["race_liara"] = new("Liara · Blend", "race_liara"),
            ["race_oldAsn"] = new("Asian · Old", "race_oldAsn"),
            ["race_oldBlk"] = new("Black · Old", "race_oldBlk"),
            ["race_oldCauc"] = new("Caucasian · Old", "race_oldCauc"),
            ["race_yngAsn"] = new("Asian · Young", "race_yngAsn"),
            ["race_yngBlk"] = new("Black · Young", "race_yngBlk"),
            ["race_yngCauc"] = new("Caucasian · Young", "race_yngCauc"),
            ["ring_Back"] = new("Cranial Ring Back", "ring_Back"),
            ["ring_Forward"] = new("Cranial Ring Forward", "ring_Forward"),
            ["ring_Large"] = new("Cranial Ring Large", "ring_Large"),
            ["ring_Small"] = new("Cranial Ring Small", "ring_Small"),
            ["rollins"] = new("Rollins", "rollins"),
            ["SAL_HED_Addn"] = new("Complexion Texture", "SAL_HED_Addn"),
            ["SAL_HED_Addn_Blend_Scalar"] = new("Complexion Strength", "SAL_HED_Addn_Blend_Scalar"),
            ["SAL_HED_Addn_Colour"] = new("Complexion Colour", "SAL_HED_Addn_Colour"),
            ["SAL_HED_Addn_Mask_Scalar"] = new("Complexion Mask Alpha", "SAL_HED_Addn_Mask_Scalar"),
            ["SAL_HED_Addn_Mask_Vector"] = new("Complexion Mask Channels", "SAL_HED_Addn_Mask_Vector"),
            ["SAL_HED_Addn_Spec_Colour"] = new("Complexion Specular Colour", "SAL_HED_Addn_Spec_Colour"),
            ["SAL_HED_Addn_Spec_Scalar"] = new("Complexion Specular Strength", "SAL_HED_Addn_Spec_Scalar"),
            ["SAL_HED_Diff"] = new("Diffuse Texture", "SAL_HED_Diff"),
            ["SAL_HED_Diff_02_Colour"] = new("Secondary Skin Colour", "SAL_HED_Diff_02_Colour"),
            ["SAL_HED_Diffuse02_Scalar"] = new("Secondary Skin Blend", "SAL_HED_Diffuse02_Scalar"),
            ["SAL_HED_EYE_Diff"] = new("Eye Diffuse Texture", "SAL_HED_EYE_Diff"),
            ["SAL_HED_EYE_Emis"] = new("Eye Emissive Strength", "SAL_HED_EYE_Emis"),
            ["SAL_HED_EYE_Iris_Vector"] = new("Iris Colour", "SAL_HED_EYE_Iris_Vector"),
            ["SAL_HED_EYE_Norm"] = new("Eye Normal Texture", "SAL_HED_EYE_Norm"),
            ["SAL_HED_EYE_Pupil_Vector"] = new("Pupil Colour", "SAL_HED_EYE_Pupil_Vector"),
            ["SAL_HED_EYE_Spec"] = new("Eye Mask and Specular Texture", "SAL_HED_EYE_Spec"),
            ["SAL_HED_Mask"] = new("Complexion and Tattoo Mask", "SAL_HED_Mask · Red = Upper Face / Green = Lower Face / Blue = Neck / Alpha = Scalp"),
            ["SAL_HED_Norm"] = new("Normal Texture", "SAL_HED_Norm"),
            ["SAL_HED_Spec_Colour"] = new("Specular Colour", "SAL_HED_Spec_Colour"),
            ["SAL_HED_Spec_Scalar"] = new("Specular Power", "SAL_HED_Spec_Scalar"),
            ["SAL_HED_SpecMap"] = new("Specular Texture", "SAL_HED_SpecMap"),
            ["SAL_HED_Tatt"] = new("Tattoo Pattern Texture", "SAL_HED_Tatt"),
            ["SAL_HED_Tatt_01"] = new("Tattoo 1 Pattern Channels", "SAL_HED_Tatt_01 · Selects the RGB channel to pull from the Tattoo Texture"),
            ["SAL_HED_Tatt_01_Scalar"] = new("Tattoo 1 Region Alpha", "SAL_HED_Tatt_01_Scalar"),
            ["SAL_HED_Tatt_01_Vector"] = new("Tattoo 1 Region Channels", "SAL_HED_Tatt_01_Vector · Selects the area to use from the Mask Texture"),
            ["SAL_HED_Tatt_02"] = new("Tattoo 2 Pattern Channels", "SAL_HED_Tatt_02 · Selects the RGB channel to pull from the Tattoo Texture"),
            ["SAL_HED_Tatt_02_Scalar"] = new("Tattoo 2 Region Alpha", "SAL_HED_Tatt_02_Scalar"),
            ["SAL_HED_Tatt_02_Vector"] = new("Tattoo 2 Region Channels", "SAL_HED_Tatt_02_Vector · Selects the area to use from the Mask Texture"),
            ["SAL_HED_Tatt_Colour"] = new("Tattoo Colour", "SAL_HED_Tatt_Colour"),
            ["SAL_HED_Tint"] = new("Surface Tint Mask", "SAL_HED_Tint · Red = Unused / Green = Secondary Skin / Blue = Unused / Alpha = Complexion"),
            ["SAL_HED_Tmis_COLOUR"] = new("Transmission Colour", "SAL_HED_Tmis_COLOUR"),
            ["Sarge"] = new("Sarge", "Sarge · Unused"),
            ["Sclera_Darken"] = new("Sclera Darkening", "Sclera_Darken"),
            ["Secondary_Reflection_Multiplier"] = new("Secondary Reflection Strength", "Secondary_Reflection_Multiplier"),
            ["shape_chubby"] = new("Face Full", "shape_chubby"),
            ["shape_skinny"] = new("Face Thin", "shape_skinny"),
            ["shape_thin"] = new("Face Thin", "shape_thin"),
            ["shell_Down"] = new("Plate Rim Down", "shell_Down"),
            ["shell_forwardSlant"] = new("Plate Rim Forward Slant", "shell_forwardSlant"),
            ["shell_thin"] = new("Inner Plates · Thin", "shell_thin"),
            ["shell_Up"] = new("Plate Rim Up", "shell_Up"),
            ["Shepard"] = new("Shepard", "Shepard"),
            ["SkinLightScattering"] = new("Skin Light Scattering", "SkinLightScattering"),
            ["SkinTone"] = new("Skin Tone", "SkinTone"),
            ["Slick"] = new("Slick", "Slick · Unused"),
            ["spike_erode"] = new("Plate Erode", "spike_erode"),
            ["spike_flare"] = new("Spikes Flare", "spike_flare"),
            ["spike_Smooth"] = new("Spikes Smooth", "spike_Smooth"),
            ["straightHairLine"] = new("Straight Hairline", "straightHairLine"),
            ["Tattoo_Chooser"] = new("Tattoo Pattern", "Tattoo_Chooser"),
            ["Tattoo_Color"] = new("Tattoo Colour", "Tattoo_Color"),
            ["teeth_Back"] = new("Teeth Back", "teeth_Back"),
            ["teeth_Canine"] = new("Teeth Canine", "teeth_Canine"),
            ["teeth_canineExtend"] = new("Teeth Canine Extend", "teeth_canineExtend · Unused"),
            ["teeth_Chiptoothleft"] = new("Teeth Chipped · Left", "teeth_Chiptoothleft"),
            ["teeth_Chiptoothright"] = new("Teeth Chipped · Right", "teeth_Chiptoothright"),
            ["teeth_close"] = new("Teeth Close", "teeth_close"),
            ["teeth_correction"] = new("Teeth Correction", "teeth_correction"),
            ["teeth_Down"] = new("Teeth Down", "teeth_Down"),
            ["teeth_Forward"] = new("Teeth Forward", "teeth_Forward"),
            ["teeth_frontTeeth"] = new("Teeth Front", "teeth_frontTeeth"),
            ["teeth_MissingLeft"] = new("Teeth Missing · Left", "teeth_MissingLeft"),
            ["teeth_Narrow"] = new("Teeth Narrow", "teeth_Narrow · Unused"),
            ["teeth_NoFront"] = new("Teeth Missing · Front", "teeth_NoFront"),
            ["teeth_Seperate"] = new("Teeth Separate", "teeth_Seperate"),
            ["teeth_Up"] = new("Teeth Up", "teeth_Up"),
            ["teeth_Wide"] = new("Teeth Wide", "teeth_Wide"),
            ["tentacle_Large"] = new("Head Crest Large", "tentacle_Large"),
            ["tentacle_long"] = new("Head Crest Long", "tentacle_long"),
            ["tentacle_Short"] = new("Head Crest Short", "tentacle_Short"),
            ["Tmission_Color"] = new("Eye Transmission Colour", "Tmission_Color"),
            ["Tmissive"] = new("Transmission Colour", "Tmissive"),
            ["TUR_EYE_Diff"] = new("Eye Diffuse Texture", "TUR_EYE_Diff"),
            ["TUR_EYE_Iris_Norm"] = new("Iris Normal Texture", "TUR_EYE_Iris_Norm"),
            ["TUR_EYE_Iris_Spec_Colour_Vector"] = new("Iris Specular Colour", "TUR_EYE_Iris_Spec_Colour_Vector"),
            ["TUR_EYE_Iris_SPwr_Scalar"] = new("Iris Specular Power", "TUR_EYE_Iris_SPwr_Scalar"),
            ["TUR_EYE_Lens_Norm"] = new("Lens Normal Texture", "TUR_EYE_Lens_Norm"),
            ["TUR_EYE_Lens_Spec_Colour_Vector"] = new("Lens Specular Colour", "TUR_EYE_Lens_Spec_Colour_Vector"),
            ["TUR_EYE_Lens_SPwr_Scalar"] = new("Lens Specular Power", "TUR_EYE_Lens_SPwr_Scalar"),
            ["TUR_EYE_Mask"] = new("Sclera and Iris Mask", "TUR_EYE_Mask"),
            ["TUR_Eye_Spec"] = new("Eye Specular Texture", "TUR_Eye_Spec"),
            ["TUR_EYE_White_Spec_Colour_Vector"] = new("Sclera Specular Colour", "TUR_EYE_White_Spec_Colour_Vector"),
            ["TUR_EYE_White_SPwr_Scalar"] = new("Sclera Specular Power", "TUR_EYE_White_SPwr_Scalar"),
            ["TUR_HED_Addn"] = new("Complexion Texture", "TUR_HED_Addn"),
            ["TUR_HED_Addn_Colour"] = new("Complexion Colour", "TUR_HED_Addn_Colour"),
            ["TUR_HED_Addn_Mask_Vector"] = new("Complexion Region Channels", "TUR_HED_Addn_Mask_Vector"),
            ["TUR_HED_Addn_Spec_Colour"] = new("Complexion Specular Colour", "TUR_HED_Addn_Spec_Colour"),
            ["TUR_HED_Diff"] = new("Diffuse Texture", "TUR_HED_Diff"),
            ["TUR_HED_Diff_02_Colour"] = new("Secondary Skin Colour", "TUR_HED_Diff_02_Colour"),
            ["TUR_HED_Diff_Tint_Bone"] = new("Bone Plate Tint", "TUR_HED_Diff_Tint_Bone"),
            ["TUR_HED_Diff_Tint_Socket"] = new("Eye Socket Tint", "TUR_HED_Diff_Tint_Socket"),
            ["TUR_HED_Diff_Tint_Teeth"] = new("Teeth Colour", "TUR_HED_Diff_Tint_Teeth"),
            ["TUR_HED_Diffuse02_Scalar"] = new("Secondary Skin Blend", "TUR_HED_Diffuse02_Scalar"),
            ["TUR_HED_Mask"] = new("Face Region Mask", "TUR_HED_Mask · Red = Brows + Forehead / Green = Middle Face / Blue = Jaw + Mandibles"),
            ["TUR_HED_Norm"] = new("Normal Texture", "TUR_HED_Norm"),
            ["TUR_HED_Spec_Colour"] = new("Skin Specular Colour", "TUR_HED_Spec_Colour"),
            ["TUR_HED_Spwr_Bone_Scalar"] = new("Bone Specular Power", "TUR_HED_Spwr_Bone_Scalar"),
            ["TUR_HED_Spwr_Skin_Scalar"] = new("Skin Specular Power", "TUR_HED_Spwr_Skin_Scalar"),
            ["TUR_HED_Tatt"] = new("Tattoo Texture", "TUR_HED_Tatt"),
            ["TUR_HED_Tatt_01"] = new("Tattoo 1 Pattern Channels", "TUR_HED_Tatt_01 · Selects the RGB channel to pull from the Tattoo Texture"),
            ["TUR_HED_Tatt_01_Scalar"] = new("Tattoo 1 Region Alpha", "TUR_HED_Tatt_01_Scalar"),
            ["TUR_HED_Tatt_01_Vector"] = new("Tattoo 1 Region Channels", "TUR_HED_Tatt_01_Vector · Selects the area to use from the Mask Texture"),
            ["TUR_HED_Tatt_02"] = new("Tattoo 2 Pattern Channels", "TUR_HED_Tatt_02 · Selects the RGB channel to pull from the Tattoo Texture"),
            ["TUR_HED_Tatt_02_Scalar"] = new("Tattoo 2 Region Alpha", "TUR_HED_Tatt_02_Scalar"),
            ["TUR_HED_Tatt_02_Vector"] = new("Tattoo 2 Region Channels", "TUR_HED_Tatt_02_Vector · Selects the area to use from the Mask Texture"),
            ["TUR_HED_Tatt_Colour"] = new("Tattoo Colour", "TUR_HED_Tatt_Colour"),
            ["TUR_HED_Tatt_Spec_Colour"] = new("Tattoo Specular Colour", "TUR_HED_Tatt_Spec_Colour"),
            ["TUR_HED_Tint"] = new("Surface Tint Mask", "TUR_HED_Tint · Red = Skin / Green = Teeth / Blue = Eye Socket"),
            ["TUR_HED_TMis_Multiplier"] = new("Transmission Strength", "TUR_HED_TMis_Multiplier"),
            ["U_Offset"] = new("Horizontal Offset", "U_Offset"),
            ["V_Offset"] = new("Vertical Offset", "V_Offset"),
            ["VorchaBase"] = new("Vorcha Base", "VorchaBase · Unused"),
            ["widowsPeak"] = new("Widow's Peak", "widowsPeak"),
            ["Willis"] = new("Willis", "Willis"),
            ["Willis01"] = new("Willis 01", "Willis01"),
            ["Wrex"] = new("Wrex", "Wrex"),
            ["Wrex_Spec_Scalar"] = new("Wrex Specular Blend", "Wrex_Spec_Scalar · Only designed for use with KRO_HED_PROWrex_Spec - should otherwise remain at 0"),
            ["X_Tile"] = new("Horizontal Tiling", "X_Tile · UV Map Tiling"),
            ["Y_Tile"] = new("Vertical Tiling", "Y_Tile · UV Map Tiling"),
        };

    private static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, MetadataText>> Archetypes =
        new Dictionary<string, IReadOnlyDictionary<string, MetadataText>>(StringComparer.OrdinalIgnoreCase)
        {
            [MorphFaceMetadataCatalogRegistry.Asari] =
                new Dictionary<string, MetadataText>(StringComparer.OrdinalIgnoreCase)
                {
                    ["cheeks_gaunt"] = new("Cheeks Gaunt", "cheeks_gaunt"),
                    ["eyes_Big"] = new("Eyes Large", "eyes_Big · Unused"),
                    ["eyes_PosDown"] = new("Eyes Pos Down", "eyes_PosDown · Unused"),
                    ["jaw_narrow"] = new("Narrow", "jaw_narrow · Unused"),
                    ["mouth_CornersDown"] = new("Mouth Corners Down", "mouth_CornersDown · Unused"),
                    ["nose_BridgeIn"] = new("Nose Bridge In", "nose_BridgeIn"),
                    ["nose_BridgeOut"] = new("Nose Bridge Out", "nose_BridgeOut"),
                    ["nose_BridgeThin"] = new("Nose Bridge Thin", "nose_BridgeThin · Unused"),
                    ["nose_BridgeWide"] = new("Nose Bridge Wide", "nose_BridgeWide"),
                    ["nose_TipDown"] = new("Nose Tip Down", "nose_TipDown"),
                    ["nose_tipNarrow"] = new("Nose Tip Narrow", "nose_tipNarrow"),
                    ["nose_TipUp"] = new("Nose Tip Up", "nose_TipUp · Unused"),
                    ["nose_tipWide"] = new("Nose Tip Wide", "nose_tipWide"),
                    ["race_oldAsn"] = new("Old Asn", "race_oldAsn · Unused"),
                    ["race_oldBlk"] = new("Old Blk", "race_iconic · Unused"),
                    ["race_oldCauc"] = new("Old Cauc", "race_oldCauc · Unused"),
                    ["race_yngAsn"] = new("Yng Asn", "race_yngAsn · Unused"),
                    ["race_yngBlk"] = new("Yng Blk", "race_yngBlk · Unused"),
                    ["race_yngCauc"] = new("Yng Cauc", "race_yngCauc · Unused"),
                },
            [MorphFaceMetadataCatalogRegistry.Batarian] =
                new Dictionary<string, MetadataText>(StringComparer.OrdinalIgnoreCase)
                {
                    ["head_ScaleUp"] = new("Scale Up", "head_ScaleUp"),
                    ["shape_chubby"] = new("Head Full", "shape_chubby"),
                    ["shape_skinny"] = new("Skinny", "shape_skinny"),
                },
            [MorphFaceMetadataCatalogRegistry.FemaleTurian] =
                new Dictionary<string, MetadataText>(StringComparer.OrdinalIgnoreCase)
                {
                    ["brow_Back"] = new("Brows Back", "brow_Back · RESERVED TUF PLACEHOLDER"),
                    ["brow_Down"] = new("Brows Down", "brow_Down · RESERVED TUF PLACEHOLDER"),
                    ["brow_Forward"] = new("Brows Forward", "brow_Forward · RESERVED TUF PLACEHOLDER"),
                    ["brow_Up"] = new("Brows Up", "brow_Up · RESERVED TUF PLACEHOLDER"),
                    ["cheeks_Down"] = new("Cheeks Down", "cheeks_Down · RESERVED TUF PLACEHOLDER"),
                    ["cheeks_Up"] = new("Cheeks Up", "cheeks_Up · RESERVED TUF PLACEHOLDER"),
                    ["eyes_Back"] = new("Eyes Back", "eyes_Back · RESERVED TUF PLACEHOLDER"),
                    ["eyes_Big"] = new("Eyes Large", "eyes_Big · RESERVED TUF PLACEHOLDER"),
                    ["eyes_Forward"] = new("Eyes Forward", "eyes_Forward · RESERVED TUF PLACEHOLDER"),
                    ["eyes_Large"] = new("Eyes Large", "eyes_Large · RESERVED TUF PLACEHOLDER"),
                    ["eyes_narrow"] = new("Eyes Narrow", "eyes_narrow · RESERVED TUF PLACEHOLDER"),
                    ["eyes_small"] = new("Eyes Small", "eyes_small · RESERVED TUF PLACEHOLDER"),
                    ["eyes_Wide"] = new("Eyes Wide", "eyes_Wide · RESERVED TUF PLACEHOLDER"),
                    ["head_ScaleUp"] = new("Head Scale Up", "head_ScaleUp · RESERVED TUF PLACEHOLDER"),
                    ["headSpikes_Long"] = new("Head Spikes Long", "headSpikes_Long · RESERVED TUF PLACEHOLDER"),
                    ["headSpikes_Short"] = new("Head Spikes Short", "headSpikes_Short · RESERVED TUF PLACEHOLDER"),
                    ["mandible_extend"] = new("Mandibles Extend", "mandible_extend · RESERVED TUF PLACEHOLDER"),
                    ["mandible_Flare"] = new("Mandibles Flare", "mandible_Flare · RESERVED TUF PLACEHOLDER"),
                    ["mandible_long"] = new("Mandibles Long", "mandible_long · RESERVED TUF PLACEHOLDER"),
                    ["mandible_retract"] = new("Mandibles Retract", "mandible_retract · RESERVED TUF PLACEHOLDER"),
                    ["mandible_Rotate"] = new("Mandibles Rotate", "mandible_Rotate · RESERVED TUF PLACEHOLDER"),
                    ["mandible_short"] = new("Mandibles Short", "mandible_short · RESERVED TUF PLACEHOLDER"),
                    ["mandible_Thick"] = new("Mandibles Thick", "mandible_Thick · RESERVED TUF PLACEHOLDER"),
                    ["mouth_Back"] = new("Mouth Back", "mouth_Back · RESERVED TUF PLACEHOLDER"),
                    ["mouth_Down"] = new("Mouth Down", "mouth_Down · RESERVED TUF PLACEHOLDER"),
                    ["mouth_Forward"] = new("Mouth Forward", "mouth_Forward · RESERVED TUF PLACEHOLDER"),
                    ["mouth_Narrow"] = new("Mouth Narrow", "mouth_Narrow · RESERVED TUF PLACEHOLDER"),
                    ["mouth_Up"] = new("Mouth Up", "mouth_Up · RESERVED TUF PLACEHOLDER"),
                    ["mouth_Wide"] = new("Mouth Wide", "mouth_Wide · RESERVED TUF PLACEHOLDER"),
                    ["neck_Thin"] = new("Neck Thin", "neck_Thin · RESERVED TUF PLACEHOLDER"),
                    ["nose_Down"] = new("Nose Down", "nose_Down · RESERVED TUF PLACEHOLDER"),
                    ["nose_In"] = new("Nose In", "nose_In · RESERVED TUF PLACEHOLDER"),
                    ["nose_Long"] = new("Nose Long", "nose_Long · RESERVED TUF PLACEHOLDER"),
                    ["nose_Narrow"] = new("Nose Narrow", "nose_Narrow · RESERVED TUF PLACEHOLDER"),
                    ["nose_Out"] = new("Nose Out", "nose_Out · RESERVED TUF PLACEHOLDER"),
                    ["nose_Short"] = new("Nose Short", "nose_Short · RESERVED TUF PLACEHOLDER"),
                    ["nose_Up"] = new("Nose Up", "nose_Up · RESERVED TUF PLACEHOLDER"),
                    ["nose_Wide"] = new("Nose Wide", "nose_Wide · RESERVED TUF PLACEHOLDER"),
                },
            [MorphFaceMetadataCatalogRegistry.HumanFemale] =
                new Dictionary<string, MetadataText>(StringComparer.OrdinalIgnoreCase)
                {
                    ["blonde"] = new("Secondary Brow Colour", "blonde"),
                    ["Eastwood"] = new("Eastwood", "Eastwood · Unused"),
                    ["eyes_Shape_droop"] = new("Shape Droop", "eyes_Shape_droop · Unused"),
                    ["eyes_Shape_sleepy"] = new("Shape Sleepy", "eyes_Shape_sleepy · Unused"),
                    ["eyes_Shape_wide"] = new("Shape Wide", "eyes_Shape_wide · Unused"),
                    ["HED_Addn_Blowout_Scalar"] = new("Primary Brow Colour Strength", "HED_Addn_Blowout_Scalar"),
                    ["HED_Addn_Colour_02_Scalar"] = new("Secondary Brow Colour Strength", "HED_Addn_Colour_02_Scalar"),
                    ["HED_Addn_Colour_Vector"] = new("Primary Brow Colour", "HED_Addn_Colour_Vector"),
                    ["HED_Addn_Spec_Lips_Scalar"] = new("Lips Specular Strength", "HED_Addn_Spec_Lips_Scalar"),
                    ["HED_Brow_Tint_Scalar"] = new("Eyeshadow Strength", "HED_Brow_Tint_Scalar"),
                    ["HED_Brow_Tint_Vector"] = new("Eyeshadow Colour", "HED_Brow_Tint_Vector"),
                    ["HED_EyeShadow_Tint_Scalar"] = new("Makeup Strength", "HED_EyeShadow_Tint_Scalar"),
                    ["HED_EyeShadow_Tint_Vector"] = new("Makeup Colour", "HED_EyeShadow_Tint_Vector"),
                    ["Mask"] = new("Scalp Opacity", "Mask · Lower values typically hide the entire scalp"),
                    ["mouth_cheekMass"] = new("Cheeks Mass", "mouth_cheekMass · Unused"),
                    ["neck_apple"] = new("Adam's Apple", "neck_apple · Unused"),
                    ["race_iconic"] = new("Iconic Shepard · Blend", "race_iconic"),
                    ["rollins"] = new("Rollins", "rollins · Unused"),
                    ["teeth_close"] = new("Teeth Close", "teeth_close · Unused"),
                    ["teeth_Seperate"] = new("Teeth Separate", "teeth_Seperate · Unused"),
                },
            [MorphFaceMetadataCatalogRegistry.HumanMale] =
                new Dictionary<string, MetadataText>(StringComparer.OrdinalIgnoreCase)
                {
                    ["eyes_Large"] = new("Large", "eyes_Large · Unused"),
                    ["eyes_lashAngle"] = new("Lashes Angle", "eyes_lashAngle"),
                    ["eyes_lashLength"] = new("Lashes Length", "eyes_lashLength"),
                    ["eyes_RotateIn"] = new("Eyes Rotate In", "eyes_RotateIn"),
                    ["eyes_RotateOut"] = new("Eyes Rotate Out", "eyes_RotateOut"),
                    ["eyeShape_droop"] = new("Droop", "eyeShape_droop · Unused"),
                    ["eyeShape_iconic"] = new("Iconic", "eyeShape_iconic · Unused"),
                    ["eyeShape_liara"] = new("Liara", "eyeShape_liara · Unused"),
                    ["eyeShape_oldBlk"] = new("Old Black", "eyeShape_oldBlk · Unused"),
                    ["eyeShape_sleepy"] = new("Sleepy", "eyeShape_sleepy · Unused"),
                    ["eyeShape_yngAsn"] = new("Young Asian", "eyeShape_yngAsn · Unused"),
                    ["HED_Lips_Tint_Vector"] = new("Lips Tint Colour", "HED_Lips_Tint_Vector"),
                    ["HED_Spec_NoBrow"] = new("Specular No Brow", "HED_Spec_NoBrow"),
                    ["Mask"] = new("Scalp Opacity", "Mask · Lower values typically hide the entire scalp"),
                    ["pupil_Small"] = new("Pupil Small (Vestigial)", "pupil_Small · Unused - it affects the lower jaw rather than pupil size and has almost no visible effect"),
                    ["race_blackOld"] = new("Black Old", "race_blackOld · Unused"),
                    ["race_Blackyng"] = new("Blackyng", "race_Blackyng · Unused"),
                    ["race_cauOld"] = new("Cau Old", "race_cauOld · Unused"),
                    ["race_cauYng"] = new("Cau Young", "race_cauYng · Unused"),
                    ["teeth_Wide"] = new("Teeth Wide", "teeth_Wide · Unused"),
                },
            [MorphFaceMetadataCatalogRegistry.Krogan] =
                new Dictionary<string, MetadataText>(StringComparer.OrdinalIgnoreCase)
                {
                    ["race_asnOld"] = new("Asn Old", "race_asnOld"),
                    ["race_asnYoung"] = new("Asn Young", "race_asnYoung"),
                },
            [MorphFaceMetadataCatalogRegistry.Salarian] =
                new Dictionary<string, MetadataText>(StringComparer.OrdinalIgnoreCase)
                {
                    ["mouth_overBite"] = new("Overbite", "mouth_overBite"),
                    ["mouth_underBite"] = new("Underbite", "mouth_underBite"),
                    ["shape_chubby"] = new("Chubby", "shape_chubby · Unused"),
                    ["shape_skinny"] = new("Face Slim", "shape_skinny"),
                },
            [MorphFaceMetadataCatalogRegistry.Turian] =
                new Dictionary<string, MetadataText>(StringComparer.OrdinalIgnoreCase)
                {
                    ["eyes_Large"] = new("Eyes Large", "eyes_Large · Unused"),
                },
            [MorphFaceMetadataCatalogRegistry.Vorcha] =
                new Dictionary<string, MetadataText>(StringComparer.OrdinalIgnoreCase)
                {
                    ["EYE_Spec_Power"] = new("Eye Specular Power", "EYE_Spec_Power"),
                    ["SkinLightScattering"] = new("Subsurface Scattering Colour", "SkinLightScattering"),
                    ["SkinTone"] = new("Skin Colour", "SkinTone"),
                },
        };

    private static readonly IReadOnlyDictionary<(MorphFaceGame Game, string Archetype), IReadOnlyDictionary<string, MetadataText>> Games =
        new Dictionary<(MorphFaceGame Game, string Archetype), IReadOnlyDictionary<string, MetadataText>>
        {
            [(MorphFaceGame.LE3, MorphFaceMetadataCatalogRegistry.Asari)] =
                new Dictionary<string, MetadataText>(StringComparer.OrdinalIgnoreCase)
                {
                    ["mouth_Forward"] = new("Mouth Forward (Vestigial)", "mouth_Forward · Has almost no visible effect, recommended to leave this value alone"),
                },
            [(MorphFaceGame.LE3, MorphFaceMetadataCatalogRegistry.HumanFemale)] =
                new Dictionary<string, MetadataText>(StringComparer.OrdinalIgnoreCase)
                {
                    ["HAIR_centerPart"] = new("Centre Part", "HAIR_centerPart · LE3 slider hidden due to this target being broken"),
                    ["HAIR_pulledBackBig"] = new("Pulled Back · Full", "HAIR_pulledBackBig · LE3 slider hidden due to this target being broken"),
                    ["HAIR_pulledBackSlick"] = new("Pulled Back · Slick", "HAIR_pulledBackSlick · LE3 slider hidden due to this target being broken"),
                    ["HAIR_sidePart"] = new("Side Part", "HAIR_sidePart · LE3 slider hidden due to this target being broken"),
                    ["HAIR_slickWidowsPeak"] = new("Slick Widow's Peak", "HAIR_slickWidowsPeak · LE3 slider hidden due to this target being broken"),
                    ["HAIR_splitSide"] = new("Split Side", "HAIR_splitSide · LE3 Only. Hidden due to this target being broken"),
                    ["HAIR_splitSide\""] = new("Split Side\"", "HAIR_splitSide\" · LE3 Only. Hidden due to this target being broken"),
                },
        };

    public static MetadataText? Resolve(string archetype, string internalName, MorphFaceGame? game = null)
    {
        if (Aliases.TryGetValue(internalName, out var canonical)) internalName = canonical;
        if (!Shared.TryGetValue(internalName, out var text)) return null;
        if (Archetypes.TryGetValue(archetype, out var local) && local.TryGetValue(internalName, out var inherited))
            text = inherited;
        if (game is { } gameKey && Games.TryGetValue((gameKey, archetype), out var variants) &&
            variants.TryGetValue(internalName, out var variant))
            text = variant;
        return text;
    }

    public static MorphFeatureMetadata Apply(string archetype, MorphFeatureMetadata metadata, MorphFaceGame? game = null)
    {
        var text = Resolve(archetype, metadata.Name, game);
        return text is null ? metadata : metadata with { Label = text.Label, Description = text.Description };
    }

    public static MaterialParameterDefinition Apply(string archetype, MaterialParameterDefinition definition, MorphFaceGame? game = null)
    {
        var text = Resolve(archetype, definition.Name, game);
        return text is null ? definition : definition with { Label = text.Label, Description = text.Description };
    }
}
