<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>MorphFaceEditor.DataCompiler</AssemblyName>
    <RootNamespace>MorphFaceEditor.DataCompiler</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\MorphFaceEditor\MorphFaceEditor.csproj" />
    <ProjectReference Include="..\..\src\MorphFaceEditor.LegendaryExplorer\MorphFaceEditor.LegendaryExplorer.csproj" />
  </ItemGroup>
</Project>
